# Generated by Django 4.1 on 2025-09-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_alter_movie_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_in_rows',
            new_name='seats_in_row',
        ),
    ]
